# Generated by Django 3.1.4 on 2020-12-09 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeheads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffee',
            name='score',
            field=models.IntegerField(blank=True, default=80),
        ),
        migrations.AlterField(
            model_name='usercoffee',
            name='add_date',
            field=models.DateField(default='2020-12-09', help_text='Enter date when u bought coffee or tried'),
        ),
    ]
