# Generated by Django 3.1.4 on 2020-12-10 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeheads', '0003_auto_20201209_1535'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coffee',
            options={'ordering': ['name'], 'verbose_name': 'coffee'},
        ),
        migrations.RemoveField(
            model_name='coffee',
            name='score',
        ),
        migrations.AlterField(
            model_name='usercoffee',
            name='add_date',
            field=models.DateField(default='2020-12-10', help_text='Enter date when u bought coffee or tried'),
        ),
    ]
