# Generated by Django 3.1.4 on 2020-12-10 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeheads', '0004_auto_20201210_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffee',
            name='add_date',
            field=models.DateField(default='2020-12-10'),
        ),
        migrations.AlterField(
            model_name='usercoffee',
            name='add_date',
            field=models.DateField(default='2020-12-10'),
        ),
    ]
