# Generated by Django 3.1.4 on 2020-12-10 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeheads', '0005_auto_20201210_1317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coffee',
            name='manufacter',
        ),
        migrations.AddField(
            model_name='coffee',
            name='manufacturer',
            field=models.CharField(default='manu', help_text='Enter coffee manufacturer', max_length=150),
            preserve_default=False,
        ),
    ]
