# Generated by Django 3.1.4 on 2020-12-19 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeheads', '0006_auto_20201210_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffee',
            name='add_date',
            field=models.DateField(default='2020-12-19'),
        ),
        migrations.AlterField(
            model_name='usercoffee',
            name='add_date',
            field=models.DateField(default='2020-12-19'),
        ),
    ]
